/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LSITools;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HereIAm
 */
public class FILES extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public FILES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        back = new javax.swing.JButton();
        button_rank = new javax.swing.JButton();
        text_location = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_query = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        but_ch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(816, 531));
        setResizable(false);
        getContentPane().setLayout(null);

        back.setText("<< BACK  ");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 470, 107, 31);

        button_rank.setText("RANK THEM");
        button_rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_rankActionPerformed(evt);
            }
        });
        getContentPane().add(button_rank);
        button_rank.setBounds(670, 470, 107, 31);

        text_location.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        text_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_locationActionPerformed(evt);
            }
        });
        getContentPane().add(text_location);
        text_location.setBounds(200, 420, 580, 40);

        text_query.setColumns(20);
        text_query.setFont(new java.awt.Font("Siyam Rupali", 0, 13)); // NOI18N
        text_query.setRows(5);
        jScrollPane1.setViewportView(text_query);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 140, 580, 275);

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel3.setText("Query Text");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 110, 118, 21);

        table.setFont(new java.awt.Font("Siyam Rupali", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                 FILES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setMaximumSize(new java.awt.Dimension(30000, 0));
        table.setMinimumSize(new java.awt.Dimension(30000, 0));
        table.setName(""); // NOI18N
        table.setRowHeight(30);
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 169, 306);

        but_ch.setText("Choose Files Location");
        but_ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_chActionPerformed(evt);
            }
        });
        getContentPane().add(but_ch);
        but_ch.setBounds(10, 420, 170, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LSITools/Capture.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_rankActionPerformed
        // TODO add your handling code here:
        
        //textf2.setText(textf.getText());
        String s=text_location.getText();
        String loc="";
        for(int i=0;i<s.length() ;i++)
            {
                if(s.charAt(i)=='\\')
                {
                    loc+="//";
                    continue;
                }
                    loc+=s.charAt(i);
                    
            }
       
        
        /*File f =new File("ADS.txt");
        try {
            f.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(FILES.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            PrintWriter out = new PrintWriter("ADS.txt");
            out.println(x);
            out.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FILES.class.getName()).log(Level.SEVERE, null, ex);
        }
        File fx =new File("Query.txt");
        try {
            fx.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(FILES.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            PrintWriter outx=new PrintWriter("Query.txt");
            outx.println(text_query.getText());
            outx.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FILES.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        if(text_location.getText().length()==0||text_query.getText().length()==0)
            JOptionPane.showMessageDialog(null, "Query or Lcation is empty !");
        else
        {
            BTest2 bt=new BTest2();

            try {
                int file=bt.main(loc,text_query.getText());
                if(file==0)JOptionPane.showMessageDialog(null, "No .txt Files Found!");
            } catch (IOException ex) {
                Logger.getLogger(FILES.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
        
        
        
   
        
    }//GEN-LAST:event_button_rankActionPerformed

    private void text_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_locationActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void but_chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_chActionPerformed

        // TODO add your handling code here:
        JFileChooser jch=new JFileChooser();
        jch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jch.setCurrentDirectory(new java.io.File(""));
        jch.showOpenDialog(this);
        String s=jch.getSelectedFile().getAbsolutePath();
       
        
        text_location.setText(s);
        String loc="";
        for(int i=0;i<s.length() ;i++)
            {
                if(s.charAt(i)=='\\')
                {
                    loc+="//";
                    continue;
                }
                    loc+=s.charAt(i);
                    
            }
        File[] files=new File(loc).listFiles();
        DefaultTableModel dt=(DefaultTableModel)(table.getModel());
        for(File f:files)
        {
            if(!f.getPath().endsWith(".txt"))continue;
            dt.addRow(new String[]{f.getName()});
        }

    }//GEN-LAST:event_but_chActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FILES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FILES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FILES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FILES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FILES().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton but_ch;
    private javax.swing.JButton button_rank;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextField text_location;
    private javax.swing.JTextArea text_query;
    // End of variables declaration//GEN-END:variables
}
//System