/*//System
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LSITools;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.Element;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author HereIAm
 */
public class WEB extends javax.swing.JFrame {

    /**
     * Creates new form WEB
     */
    public WEB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_show = new javax.swing.JTextArea();
        mine = new javax.swing.JButton();
        url = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        query = new javax.swing.JTextArea();
        sum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(816, 531));
        setMinimumSize(new java.awt.Dimension(816, 531));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("* DEPENDS ON YOUR BANDWIDTH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(610, 30, 190, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("* EDITABLE BEFORE SUMMARIZE ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 50, 190, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("* NOT FOR ENGLISH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(610, 10, 140, 20);

        text_show.setColumns(20);
        text_show.setFont(new java.awt.Font("Siyam Rupali", 0, 13)); // NOI18N
        text_show.setRows(5);
        jScrollPane1.setViewportView(text_show);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 796, 230);

        mine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mine.setText("<< Mine Data From This URL");
        mine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mineActionPerformed(evt);
            }
        });
        getContentPane().add(mine);
        mine.setBounds(570, 350, 232, 46);
        getContentPane().add(url);
        url.setBounds(0, 350, 554, 46);

        query.setColumns(20);
        query.setFont(new java.awt.Font("Siyam Rupali", 0, 13)); // NOI18N
        query.setRows(5);
        jScrollPane2.setViewportView(query);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 400, 554, 102);

        sum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sum.setText("<< Summarize On This Query");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        getContentPane().add(sum);
        sum.setBounds(570, 400, 232, 102);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LSITools/Capture.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String plain="";
    private void mineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mineActionPerformed
                // TODO add your handling code here:
        
        if(url.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "URL is empty !");
        }
        else
        {
            String html = url.getText();
            Document doc;
             String str="";
             String take="";
             
             //String qr=query.getText();
            try {
              doc = Jsoup.connect(html).get();
               str=doc.toString();
               String bad="\\/|$]}_*-^#&%+[{”“.1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:#/,@৳%&*()'\";-=\n\r><?!।"; // this character will be removed
               for(int j=0;j<str.length();j++)
               {
                   int i;
                   for( i=0;i<bad.length()-5;i++)
                       if(str.charAt(j)==bad.charAt(i))
                            break;
                   if(i==bad.length()-5)take+=str.charAt(j);
                   
               }
               /*for(int i=0;i<bad.length()-3;i++)
                {
                  str=str.replace( bad.charAt(i), ' ');
                  
                  //qr=qr.replace( bad.charAt(i), ' ');
                }*/// oproyojonio symbol bad jacce
               //qr+="।";
               str=take;
               str=str.replace( '?', '।');
               str=str.replace( '!', '।');
               str=str.replace( '>', '।');
               str=str.replace( '<', '।');
               String [] sens = str.split("।");
               str="";
               for(String tmp:sens)
               {
                   //tmp=tmp.replaceAll("  "," ");
                   //if(tmp.length()<5)continue;
                   int cnt=2;
                   String stmp="";
                   for(int i=0;i<tmp.length();i++)
                   {
                      if(tmp.charAt(i)==' ')
                          cnt++;
                      else cnt=0;
                      if(cnt<=1)stmp+=tmp.charAt(i);
                      
                   }
                   if(stmp.length()<3)continue;
                   str+=stmp;
                   plain+=stmp+'।';
                   
                   str+='\n';
               }
                text_show.setText(str);
                } catch (IOException ex) {
                Logger.getLogger(WEB.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
          
            
                    //
        


    }//GEN-LAST:event_mineActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        // TODO add your handling code here:
        if(url.getText().isEmpty()||query.getText().isEmpty()||text_show.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Query or URL is empty !");
        }
        else
        {
            BTest1 bt=new BTest1();
            try {
                
                String qr=query.getText();
                qr+='।'; 
                
                bt.main(text_show.getText(),qr, url.getText());
            } catch (IOException ex) {
                Logger.getLogger(WEB.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_sumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WEB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mine;
    private javax.swing.JTextArea query;
    private javax.swing.JButton sum;
    private javax.swing.JTextArea text_show;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables
}
